costio/costio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('costio_web.urls')),
    path('api/', include('costio_api.urls'))
]

costio/costio_api/urls.py
from django.urls import path
from rest_framework.authtoken import views as authviews
from . import views

app_name = 'costio_api'
urlpatterns = [
    path('login/', authviews.obtain_auth_token),
    path('expenses/', views.ExpensesView.as_view())
]

costio/costio_web/urls.py
from django.urls import path
from . import views

app_name = 'costio'
urlpatterns = [
    # User auth views
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Registration.as_view(), name='registration'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('expenses/', views.ExpenseList.as_view(), name='expense_list'),
    path('expenses/create/', views.ExpenseCreate.as_view(), name='expense_create'),
    path('expenses/delete/<int:pk>', views.ExpenseDelete.as_view(), name='expense_delete')
]

costio/costio_api/models.py
from django.db import models

# Create your models here.

costio/costio_web/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models
from django.db.models import fields
# Create your models here.


class Category(models.Model):
    name = fields.CharField(max_length=100)

    def __str__(self):
        return self.name


class Expense(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    name = fields.CharField(default='Expense', max_length=50)
    cost = fields.IntegerField()
    date_of_creation = fields.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

costio/costio_web/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import Expense

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        exclude = ['date_of_creation', 'user']

costio/costio_api/views.py
from django.shortcuts import render
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from costio_web.models import Expense
from .serializers import ExpenseSerializer
# Create your views here.

class ExpensesView(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = ExpenseSerializer

    def get_queryset(self):
        return Expense.objects.filter(user=self.request.user)

costio/costio_web/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from costio_web.models import Expense, Category
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from . import forms
from .mixins import LoginRequiredNoNextMixin
from django.urls import reverse_lazy
from django.db.models import Sum


class IndexView(LoginRequiredNoNextMixin, generic.RedirectView):
    url = reverse_lazy('costio:expense_list')


class Login(LoginView):
    redirect_field_name = ''
    redirect_authenticated_user = True
    authentication_form = forms.LoginForm


class Logout(LogoutView):
    url = reverse_lazy('costio:login')

    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        return super().get_redirect_url()


class Registration(generic.CreateView):
    form_class = forms.RegistrationForm
    template_name = 'registration/register.html'
    success_url = '/login'


class ExpenseList(LoginRequiredNoNextMixin, generic.ListView):
    model = Expense
    template_name = 'costio_web/expenses_list.html'

    def get_queryset(self):
        return Expense.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['expense_list'] = Expense.objects.filter(
            user=self.request.user
        )
        context['expenses_data'] = Expense.objects.filter(
            user=self.request.user
        ).aggregate(expenses_sum=Sum('cost'))['expenses_sum']
        return context


class ExpenseCreate(LoginRequiredNoNextMixin, generic.CreateView):
    model = Expense
    form_class = forms.ExpenseForm
    template_name = 'costio_web/expense_create.html'

    def form_valid(self, form):
        expense = form.save(commit=False)
        expense.user = User.objects.get(id=self.request.user.id)
        expense.save()
        return HttpResponseRedirect(reverse_lazy('costio:expense_list'))


class ExpenseDelete(LoginRequiredNoNextMixin, generic.DeleteView):
    model = Expense
    template_name = 'costio_web/expense_delete.html'
    success_url = reverse_lazy('costio:expense_list')

costio/costio_web/templates/costio_web/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Costio</title>
</head>
<body>
<h1>Costio</h1>
<a href="{% url 'costio:logout' %}">Log out</a>
{% block content %}

{% endblock %}
</body>
</html>

costio/costio_web/templates/costio_web/expense_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>
</body>
</html>

costio/costio_web/templates/costio_web/expense_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action="{% url 'costio:expense_delete' object.id %}">
    {% csrf_token %}
    <p>Are you sure?</p>
    <input type="submit" value="Delete">
</form>
</body>
</html>

costio/costio_web/templates/costio_web/expenses_list.html
{% extends 'costio_web/base_template.html' %}
{% block content %}
<h1>Your Expenses and Incomes</h1>
<h2>Your balance: {{expenses_data}}</h2>
<a href="{% url 'costio:expense_create' %}">Add Expense</a>
{% for expense in expense_list %}
    <ul>
        <li>
            {{expense.category}}
        </li>
        <li>
            {{expense.cost}}
        </li>
    </ul>
<a href="{% url 'costio:expense_delete' expense.id %}">Delete</a>
{% endfor %}
{% endblock %}